#!/usr/bin/env bash

#############################################################################
# Initialize common variables
#############################################################################
# Gets the directory of ../.. relative to this script, which should be the root directory of the project
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)" 
nerrors=0
RECOVERY_TOOL="$PROJECT_DIR/utils/vfd_swmr/recovery_tool"
CRASHER_TOOL="$PROJECT_DIR/utils/vfd_swmr/crasher"
VFD_GENERATOR="$PROJECT_DIR/test/vfd_swmr_generator"

# Functionality exists to run the crash loop for each test with multiple
#  sets of options. This can take a really long time, so this variable
#  causes the script to only run the first set of options for each test.
ONLY_RUN_EACH_TEST_ONCE=true 


# Set paths to HDF5 tools
H5CLEAR="$PROJECT_DIR/install/bin/h5clear"
H5DUMP="$PROJECT_DIR/install/bin/h5dump"
H5LS="$PROJECT_DIR/install/bin/h5ls"
export H5CLEAR_PATH="$H5CLEAR" # for h5clear call within recovery_tool.c

HDF5_NOCLEANUP=1 # Set to a non-empty value to prevent cleanup of output files. 

KEEP_OUTPUT_FILES=false # forces recovery and validation output files to be kept for each iteration.
VERBOSE=false

###############################################################################
# HDF5TestExpress variable controls how exhaustive the tests are.
## 0:  Exhaustive run: Tests take a long time to run.
## 1:  Default run.
## 2+: Quick run (not implemented into this script)
###############################################################################
if [[ -z $HDF5TestExpress ]]; then    # Set to default when not set
    HDF5TestExpress=1
fi

# Declare verbosity printing function
# Using printf instead of echo because to support better text formatting
vprintf() {
    if $VERBOSE; then
        printf "$@"
    fi
}

# Set up test directory
rm -rf crash_test
mkdir crash_test
cd crash_test


###############################################################################
# configure_test_env() <test_name>
#   Arguments:
#     $1 - test name (standard, bigset, sparse, remove)
# Configure environment variables to run each test
# NOTE: This function was created for the purpose of handling multiple 
#       test cases in the crash recovery script. For now, only the "bigset"
#       test has been fully implemented and tested.
################################################################################
configure_test_env() {
    case "$1" in
        standard)
            WRITER_TOOL="$PROJECT_DIR/test/vfd_swmr_writer"
            EXPECTED_H5_FILE="vfd_swmr_data.h5"
            EXPECTED_UD_FILE="rw-updater" 
            WRITER_OPTIONS="-W -o 200000"
            if [[ "$HDF5TestExpress" -eq 0 ]] ; then # exhaustive run
                WRITER_OPTIONS="-W -o 40000"
            fi
            REQUIRES_GENERATOR=true # Some writers only modify an existing h5 file generated by vfd_swmr_generator
            
            # Different configs that can be optionally tested
            GENERATOR_CONFIGS=("-s -i ea" "-s -i b2")

            if [[ "$HDF5TestExpress" -eq 0 ]] ; then # exhaustive run
                GENERATOR_CONFIGS+=("-s -c 5 -i ea" "-s -c 5 -i b2")
            fi
            ;;

        bigset)
            WRITER_TOOL="$PROJECT_DIR/test/vfd_swmr_bigset_writer"
            EXPECTED_H5_FILE="vfd_swmr_bigset.h5"
            EXPECTED_UD_FILE="bigset_updater"
            WRITER_OPTIONS="-d 1 -t -l 10 -e 8 -r 256 -c 256 -q -N -R" # common options for bigset writer

            if [[ "$HDF5TestExpress" -eq 0 ]] ; then # exhaustive run
                WRITER_OPTIONS="-n 100 -s 25 $WRITER_OPTIONS"
            elif [[ "$HDF5TestExpress" -gt 1 ]] ; then # quick run
                WRITER_OPTIONS="-n 10 -s 3 $WRITER_OPTIONS"
            else # default run
                WRITER_OPTIONS="-n 25 -s 10 $WRITER_OPTIONS"
            fi

            VALIDATION_OPTIONS="$WRITER_OPTIONS -S"
            REQUIRES_GENERATOR=false
            GENERATOR_CONFIGS=("")
            ;;

        # THESE TESTS NEED TO BE MODIFIED TO WORK.
        sparse)
            WRITER_TOOL="$PROJECT_DIR/test/vfd_swmr_sparse_writer"
            EXPECTED_H5_FILE="vfd_swmr_data.h5"
            EXPECTED_UD_FILE="sparse-updater"
            WRITER_OPTIONS="-W 20000"
            REQUIRES_GENERATOR=true # Some writers only modify an existing h5 file generated by vfd_swmr_generator
            GENERATOR_CONFIGS=("-s -i ea" "-s -i b2")

            if [[ "$HDF5TestExpress" -eq 0 ]] ; then # exhaustive run
                GENERATOR_CONFIGS+=("-s -c 5 -i ea" "-s -c 5 -i b2")
            fi

            ;;

        remove)
            WRITER_TOOL="$PROJECT_DIR/test/vfd_swmr_remove_writer"
            EXPECTED_H5_FILE="vfd_swmr_data.h5"
            EXPECTED_UD_FILE="remove-updater"
            WRITER_OPTIONS="-W 40000"
            REQUIRES_GENERATOR=true # Some writers only modify an existing h5 file generated by vfd_swmr_generator
            GENERATOR_CONFIGS=("-s -i ea" "-s -i b2")

            if [[ "$HDF5TestExpress" -eq 0 ]] ; then # exhaustive run
                GENERATOR_CONFIGS+=("-s -c 5 -i ea" "-s -c 5 -i b2")
            fi

            ;;

            *)
            echo "Unknown test case: $1"
            return 1
            ;;
    esac

    WRITER_NAME=$(basename $WRITER_TOOL)

} # configure_test_env()


###############################################################################
# catch_out_err_and_rc outbase command [arguments]
#
# Run `command` with any `arguments` provided.  Redirect `command`'s
# stderr and stdout to the file `${outbase}.out`.  Record the result code
# of `command` in `${outbase}.rc`.
###############################################################################
catch_out_err_and_rc()
{
    if [ $# -lt 2 ]; then
        echo "usage: catch_output_and_rc outbase command [arguments]" \
            1>&2
        exit 1
    fi
    outbase=$1
    shift

    eval "$*" > ${outbase}.out 2>&1 &
    wait $!
    echo $? > ${outbase}.rc
} # catch_out_err_and_rc()

###############################################################################
# keep_output_files() <count>
#
# Arguments:
#   $1 - count: The crash loop iteration count, to distinguish different output
#        files from crash loop for a given test.
#
# Renames recovery tool and validation output so files won't be rewritten in 
#  next iteration of the crash loop, or in the next test. Uses global $test_name
#  variable
#  Used for debugging.
###############################################################################
keep_output_files() {
    count=$1
    # rename the output files so they don't get overwritten
    if [ -f $WRITER_NAME.out ]; then
        mv $WRITER_NAME.out $WRITER_NAME.out.$count
    fi
    if [ -f ${test_name}_recovery.out ]; then 
        mv ${test_name}_recovery.out ${test_name}_recovery.out.$count
    fi
    if [ -f ${test_name}_validation_pre.out ]; then
        mv ${test_name}_validation_pre.out ${test_name}_validation_pre.out.$count
    fi
    if [ -f ${test_name}_validation_post.out ]; then
        mv ${test_name}_validation_post.out ${test_name}_validation_post.out.$count
    fi
    if [ -f ${test_name}_h5clear_pre.out ]; then
        mv ${test_name}_h5clear_pre.out ${test_name}_h5clear_pre.out.$count
    fi
    if [ -f h5clear_post.out ]; then
        mv h5clear_post.out ${test_name}_h5clear_post.out.$count
    fi
} # keep_output_files()

###############################################################################
# run_test_case() <delay> <count>
# Function to test a single point in the crash recovery test.
# - Arguments:
#   $1 - delay: seconds before the writer tool is killed
#   $2 - count: iteration number for current test. Used for naming output files.
# - Processes:
#   1. Runs the writer tool with the specified crash delay, expecting it to
#      crash itself after the delay.
#   2. Runs h5clear to reset the status flags of the HDF5 file.
#   3. Attempts to validate the HDF5 file before recovery using the validation 
#      tool. (This will check if the HDF5 file is readable before recovery.)
#   4. Runs the recovery tool to recover the HDF5 file using updater files.
#      (The recovery tool also resets the status flags of the HDF5 file after
#      applying the updater files.)
#   5. Validates the HDF5 file after recovery using the validation tool.
#      (This will check if the HDF5 file is readable after recovery.)
#   6. If $KEEP_OUTPUT_FILES is true: Renames output files so they wont be 
#      overwritten.
#   7. If $HDF5_NOCLEANUP is undefined: Cleans up any files created 
#      during the test (not including files that were renamed in step 6).
# - Returns:
#   0 - Either all tests are successful, or the test encountered a soft error
#       that is not critical and is exiting early, but without a failure.
#   1 - The test encountered a hard error, such as the recovery tool failing.
#       Stops test entirely.
#################################################################################
run_test_case() {
    local delay=$1
    local count=$2
    
    #=======================================================================
    # GENERATOR TOOL
    #   Some writer tools require an existing HDF5 file to modify.
    #   In those cases, run the generator tool to create the initial file.
    #=======================================================================
    if $REQUIRES_GENERATOR; then
        vprintf "%-32s : " "GENERATOR TOOL"
        catch_out_err_and_rc generator \
        $VFD_GENERATOR $generator_config
        rc=$(cat generator.rc)

        if [ $rc -ne 0 ]; then
            echo "Generator failed with rc=$rc. Exiting."
            nerrors=$((nerrors + 1))
            return 1
        else
            vprintf "Generator succeeded.\n"
        fi    
    fi

    #=======================================================================
    # WRITER TOOL         
    #   Run the writer tool and crash after $delay seconds
    #=======================================================================
    vprintf "%-32s : " "$WRITER_NAME"
    # Crasher tool handles output redirection so no need for catch_out_err_and_rc
    $CRASHER_TOOL $delay $WRITER_TOOL $WRITER_OPTIONS 
    rc=$(cat $WRITER_NAME.rc)

    # Check the return code of the writer tool
    if [ "$rc" -eq 0 ]; then
        # Writer tool had enough time to finish writing the file.
        vprintf "NORMAL EXIT -- no crash, stopping test\n"
        finished=1
    elif [ "$rc" -eq 137 ]; then
        # Writer tool was killed, which is expected.
        vprintf "CRASHED -- killed after $delay seconds\n"
    else
        echo "ERROR (rc=$rc) -- check writer log. ENDING TEST."
        nerrors=$((nerrors + 1))
        return 1
    fi


    #=======================================================================
    # PRE-RECOVERY H5CLEAR
    #   We need to clear the status flags on the HDF5 file before trying to
    #   do pre-recovery validation. Otherwise the validation tools won't be
    #   able to open the file. This is not required after recovery because
    #   the recovery tool already does this as part of the recovery process.
    #=======================================================================
    vprintf "%-32s : " "H5CLEAR -s"
    if [ -f $EXPECTED_H5_FILE ]
    then
        catch_out_err_and_rc ${test_name}_h5clear_pre \
           $H5CLEAR -s $EXPECTED_H5_FILE
        rc=$(cat ${test_name}_h5clear_pre.rc)
    else
        vprintf "FAILED -- $EXPECTED_H5_FILE does not exist\n"
        return 0
    fi

    if [ $rc -ne 0 ]; then
        vprintf "FAILED (rc = $rc)\n"
    else
        vprintf "SUCCEEDED\n"
    fi


    #=======================================================================
    # PRE-RECOVERY VALIDATION
    #   Uses the validation tool(s) to check if the H5 file is readable 
    #   before recovery.
    #=======================================================================
    vprintf "%-32s : " "PRE-RECOVERY VALIDATION"
    if [ -f $EXPECTED_H5_FILE ]
    then
        # Run validation on the H5 file with h5ls
        catch_out_err_and_rc ${test_name}_validation_pre \
            $H5LS $EXPECTED_H5_FILE
        rc=$(cat ${test_name}_validation_pre.rc)

        # Run H5DUMP to further validate recovery
        if [[ $rc -eq 0 ]] ; then
            printf "\nRunning H5DUMP for further validation.\n" >> ${test_name}_validation_pre.out
            $H5DUMP -pH $EXPECTED_H5_FILE >> ${test_name}_validation_pre.out 2>&1 
            rc=$?
        fi

    else # should not be possible since we checked for file existence in h5clear step
        vprintf "FAILED -- $EXPECTED_H5_FILE does not exist\n"
        nerrors=$((nerrors + 1))
        return 0
    fi

    if [ $rc -ne 0 ]; then
        vprintf "FAILED (rc = $rc)\n"
    else
        vprintf "SUCCEEDED -- Pre-recovery validation passed\n"
    fi

    #=======================================================================
    # RECOVERY TOOL
    #   Attempt to recover the H5 file using the updater files.
    #=======================================================================
    vprintf "%-32s : " "RECOVERING H5 FILE"
    # Now try to recover the H5 file by applying the updater files using 
    # athe recovery tool.
    if [ -f "$EXPECTED_UD_FILE.0" ]
    then
        catch_out_err_and_rc ${test_name}_recovery \
            $RECOVERY_TOOL $EXPECTED_H5_FILE $EXPECTED_UD_FILE
        rc=$(cat ${test_name}_recovery.rc)
    else
        vprintf "FAILED -- $EXPECTED_UD_FILE.0 does not exist\n"
        return 0
    fi

    # Check the return code of the recovery tool
    if [ "$rc" -ne 0 ]; then
        echo "FAILED (rc = $rc) ... Check ${test_name}_recovery.out. ENDING TEST."
        nerrors=$((nerrors + 1))
        return 1
    else
        vprintf "SUCCEEDED -- Updater files applied\n"
    fi


    #=======================================================================
    # POST-RECOVERY VALIDATION
    #   Uses the validation tool(s) to check if the H5 file is readable
    #   after recovery.
    #=======================================================================
    vprintf "%-32s : " "POST-RECOVERY VALIDATION"
    if [ -f $EXPECTED_H5_FILE ]
    then
        # Run validation on the recovered H5 file
        catch_out_err_and_rc ${test_name}_validation_post \
            $H5LS $EXPECTED_H5_FILE
        rc=$(cat ${test_name}_validation_post.rc)

        # Run H5DUMP to further validate recovery
        if [[ $rc -eq 0 ]] ; then
            printf "\nRunning H5DUMP for further validation.\n" >> ${test_name}_validation_post.out
            $H5DUMP -pH $EXPECTED_H5_FILE >> ${test_name}_validation_post.out 2>&1 
            rc=$?
        fi
        
    else # should not be possible since we checked for file existence in recovery step
        vprintf "FAILED -- $EXPECTED_H5_FILE does not exist\n"
        nerrors=$((nerrors + 1))
        return 0
    fi

    if [ $rc -ne 0 ]; then
        vprintf "FAILED (rc = $rc)\n"
    else
        vprintf "SUCCEEDED -- Post-recovery validation passed\n"
    fi


    #=======================================================================
    # OUTPUT FILE HANDLING
    #   Rename output files if KEEP_OUTPUT_FILES is true
    #   If HDF5_NOCLEANUP is not set, remove all output files (that haven't
    #   been renamed)
    #=======================================================================
    if $KEEP_OUTPUT_FILES; then
        # Rename the output files so they don't get deleted in the cleanup step
        keep_output_files $count
    fi

    # Clean up output files
    if test -z "$HDF5_NOCLEANUP"; then
        rm -f $EXPECTED_H5_FILE
        rm -f ${test_name}_recovery.out ${test_name}_recovery.rc 
        rm -f $WRITER_NAME.out $WRITER_NAME.rc 
        rm -f ${test_name}_h5clear_pre.out ${test_name}_h5clear_pre.rc 
        rm -f h5clear_post.out h5clear_post.rc 
        rm -f ${test_name}_validation_pre.out ${test_name}_validation_pre.rc 
        rm -f ${test_name}_validation_post.out ${test_name}_validation_post.rc
        rm -f $EXPECTED_UD_FILE.[0-9]* # Remove all updater files
        rm -f VFD_SWMR_WRITER_MESSAGE

        if $REQUIRES_GENERATOR; then
            rm -f generator.out generator.rc
        fi

        # The catch_out_err_and_rc() function USED to create pid files, but that functionality has
        # been removed. Thus, the following cleanup is not necessary anymore, but has been left here
        # in case we want to re-add pid file functionality later.
        if false; then
            rm -f ${test_name}_recovery.pid $WRITER_NAME.pid h5clear.pid h5clear_post.pid 
            rm -f ${test_name}_validation_pre.pid ${test_name}_validation_post.pid
            if $REQUIRES_GENERATOR; then rm -f generator.pid ; fi
        fi
    fi

    return 0
} # run_test_case()


run_crash_recovery_loop() {
    local sec=0
    local msec=0
    local delay
    local count=0
    finished=0

    while [ $finished -eq 0 ] 
    do
        # Simple way to format the delay in seconds and milliseconds
        delay=$(printf "%d.%03d" "$sec" "$msec")
        
        vprintf "\nTesting with delay: $delay seconds ... \n\n"
        run_test_case $delay $count
        
        if [ $? -ne 0 ]; then
            echo "ERROR: run_test_case failed for delay $delay"
            return 1
        fi

        count=$((count + 1))

        # Increment timing for next iteration
        msec=$((msec + 100))
        if [ $msec -ge 1000 ]; then
            msec=0
            sec=$((sec + 1))
        fi
    done
    
    return 0
} # run_crash_recovery_loop()



# Usage function
usage() {
    echo "Usage: $0 [-h] [-v] [-k] [test1 test2 ...]"
    echo ""
    echo "Run crash recovery tests for VFD SWMR"
    echo "For each test iteration, the writer tool will be executed and then crashed after"
    echo "a specified delay. The HDF5 file will then be recovered using the updater files."
    echo "The H5LS and H5DUMP utilities will be used both before and after recovery to verify that"
    echo "the recovery process was successful."
    echo ""
    echo "Options:"
    echo "  -h        Show this help message and exit"
    echo "  -v        Enable verbose output"
    echo "  -k        Keep output files from each iteration. Useful for debugging."
    echo "            WILL GENERATE DOZENS OF FILES."
    echo ""
    echo "Files kept with -k option:"
    echo "  <test>_recovery.out.<count>            - Recovery tool output and error messages"
    echo "  <test>_h5clear_pre.out.<count>         - H5clear status reset before validation"
    echo "  <test>_h5clear_post.out.<count>        - H5clear status reset after validation"
    echo "  <test>_validation_pre.out.<count>      - File validation before recovery"
    echo "  <test>_validation_post.out.<count>     - File validation after recovery"
    echo "  <writer_tool>.out.<count>              - Writer tool output and error messages"
    echo ""
    echo "  Where <test> is the test name (standard, bigset, sparse, or remove), <count> is the iteration number"
    echo "  and <writer_tool> is the name of the actual writer program used in the test."
    echo ""
    echo "  NOTE: a single test goes through dozens of iterations, so a large number of files will be created."
    echo ""
    echo "Tests:"
    echo "  standard  Run standard writer crash test (vfd_swmr_writer)"
    echo "  bigset    Run bigset writer crash test (vfd_swmr_bigset_writer)"  
    echo "  sparse    Run sparse writer crash test (vfd_swmr_sparse_writer)"
    echo "  remove    Run remove writer crash test (vfd_swmr_remove_writer)"
    echo " If no tests are specified, all tests will be run."
    echo ""
    echo "All output files are placed in a newly made crash_test/ directory inside the current working directory."
    echo ""
    echo "Examples:"
    echo "  $0                    # Run all tests"
    echo "  $0 -v -k standard     # Run standard test with verbose output and keep files"
    echo "  $0 bigset sparse      # Run only bigset and sparse tests"
    echo ""
} # usage()

# Parse command line arguments
parse_args() {
    local tests_to_run=()
    
    while [[ $# -gt 0 ]]; do
        case $1 in
            -h)
                usage
                exit 0
                ;;
            -v)
                VERBOSE=true
                shift
                ;;
            -k)
                KEEP_OUTPUT_FILES=true
                shift
                ;;
        # We only support bigset right now, so no need to allow user to select tests.
        #  Expected to add these tests back in later.
            standard|bigset|sparse|remove)
                tests_to_run+=("$1")
                shift
                ;;
            -*)
                echo "Unknown option: $1"
                usage
                exit 1
                ;;
            *)
                echo "Unknown test: $1"
                echo "Valid tests: standard, bigset, sparse, remove"
                usage
                exit 1
                ;;
        esac
    done
    
    # If no tests specified, run all tests
    if [ ${#tests_to_run[@]} -eq 0 ]; then
        tests_to_run=("standard" "bigset" "sparse" "remove")
    fi
    
    # Export the tests array so other functions can use it
    selected_tests=("${tests_to_run[@]}")
} # parse_args()

# Main function to run the crash recovery test
main() {
    # Parse command line arguments first
    parse_args "$@"
    vprintf "========================================================================\n"
    vprintf "Running crash recovery test loop on tests: ${selected_tests[*]}\n"
    vprintf "========================================================================\n"
    echo "HDF5TestExpress = $HDF5TestExpress"

    for test_name in "${selected_tests[@]}"; do
        echo ""
        echo "########## Running test: $test_name ##########"

        configure_test_env "$test_name"
        # set up nested loop to handle all different configs that can be run in a test.
        local has_run=false # Needed to skip additional configs if ONLY_RUN_EACH_TEST_ONCE is true
        for generator_config in "${GENERATOR_CONFIGS[@]}"; do

            # Skip additional configs if ONLY_RUN_EACH_TEST_ONCE is true and this test has already run once.
            if $ONLY_RUN_EACH_TEST_ONCE && $has_run; then
                continue  # Skip THIS test's additional configs
            fi
    
            vprintf "\nTest Configuration:\n"
            vprintf "    Writer:           %s <delay> %s %s\n" "$CRASHER_TOOL" "$WRITER_TOOL" "$WRITER_OPTIONS"
            vprintf "    Validation:       %s && %s\n" "$H5LS $EXPECTED_H5_FILE" "$H5DUMP -pH $EXPECTED_H5_FILE"
            vprintf "    Expected files:   %s, %s.*\n" "$EXPECTED_H5_FILE" "$EXPECTED_UD_FILE"
            vprintf "    Recovery:         %s\n" "$RECOVERY_TOOL"
            vprintf "    H5Clear:          %s -s\n" "$H5CLEAR"
            
            if $REQUIRES_GENERATOR && [ -n "$generator_config" ]; then
                vprintf "    Generator:        %s %s\n" "$VFD_GENERATOR" "$generator_config"
            else
                vprintf "    Generator:        None\n"
            fi
            vprintf "\n"

            run_crash_recovery_loop

            has_run=true # Used to skip subsequent configurations for the same test
        done
    done    
    
    echo "Crash recovery test finished."
    echo "Total Critical Errors: $nerrors" # should only ever be 0 or 1
} # main()

main "$@" # Run the script
