name: hdf5 dev cmake CI
on: 
  push:
    branches: [ i386 ]
  pull_request:
    branches: [ i386 ]


# Using concurrency to cancel any in-progress job or run
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
    call-release-cmake-i386:
        name: "CMake i386 Workflows"
        uses: ./.github/workflows/i386-cmake.yml
        with:
            build_mode: "Release"
