name: hdf5 dev cmake CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_call:

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel. We just have one job, but the matrix items defined below will
# run in parallel.
jobs:

    call-release-cmake-cygwin:
        name: "CMake Cygwin Workflows"
        uses: ./.github/workflows/cygwin-cmake.yml
        with:
            build_mode: "Release"
            